export const caRegistrationInitialValues = {
  firstName: '',
  lastName: '',
  email: '',
  password: '',
  confirmPassword: '',
  phone: '',
  alternatePhone: '',

  caDesignation: '',
  caNumber: '',
  provinceOfRegistration: '',
  yearAdmitted: '',
  yearsOfExperience: '',
  firmName: '',
  firmWebsite: '',
  areasOfExpertise: [],
  languages: [],
  otherLanguage: '',
  professionalDesignations: [],

  firmAddress: '',
  city: '',
  province: '',
  firmPostalCode: '',
  firmCountry: 'Canada',
  firmPhone: '',
  firmEmail: '',
  firmSize: '',
  numberOfPartners: '',
  numberOfStaff: '',
  yearEstablished: '',

  professionalLiabilityInsurance: false,
  insuranceProvider: '',
  policyNumber: '',
  policyExpiryDate: '',
  licenseDocument: null,
  insuranceDocument: null,
  peerReviewCompleted: false,
  peerReviewDate: '',
  practiceType: '',
  taxServicesOffered: [],
  clientTypesServed: [],
  industriesServed: [],
  serviceAreas: [],

  caCertificateFile: null,
  professionalHeadshotFile: null,
  firmLogoFile: null,
  referenceName: '',
  referenceEmail: '',
  authorizeCredentialCheck: false,

  agreedTermsAndConditions: false,
  agreedPrivacyPolicy: false,
  agreedProfessionalTerms: false,
  confirmAccuracy: false
};